/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface CheckResponse
 */
export interface CheckResponse {
    /**
     * 
     * @type {User}
     * @memberof CheckResponse
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof CheckResponse
     */
    userId: string;
}

/**
 * Check if a given object implements the CheckResponse interface.
 */
export function instanceOfCheckResponse(value: object): value is CheckResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CheckResponseFromJSON(json: any): CheckResponse {
    return CheckResponseFromJSONTyped(json, false);
}

export function CheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'userId': json['userId'],
    };
}

export function CheckResponseToJSON(value?: CheckResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserToJSON(value['user']),
        'userId': value['userId'],
    };
}

