/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedUrlPostResponse
 */
export interface FeedUrlPostResponse {
    /**
     * 
     * @type {string}
     * @memberof FeedUrlPostResponse
     */
    feedUrl: string;
}

/**
 * Check if a given object implements the FeedUrlPostResponse interface.
 */
export function instanceOfFeedUrlPostResponse(value: object): value is FeedUrlPostResponse {
    if (!('feedUrl' in value) || value['feedUrl'] === undefined) return false;
    return true;
}

export function FeedUrlPostResponseFromJSON(json: any): FeedUrlPostResponse {
    return FeedUrlPostResponseFromJSONTyped(json, false);
}

export function FeedUrlPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedUrlPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'feedUrl': json['feedUrl'],
    };
}

export function FeedUrlPostResponseToJSON(value?: FeedUrlPostResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'feedUrl': value['feedUrl'],
    };
}

