/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WithUUIDUserPublic } from './WithUUIDUserPublic';
import {
    WithUUIDUserPublicFromJSON,
    WithUUIDUserPublicFromJSONTyped,
    WithUUIDUserPublicToJSON,
} from './WithUUIDUserPublic';

/**
 * 
 * @export
 * @interface FriendsRequestGetResponse
 */
export interface FriendsRequestGetResponse {
    /**
     * 
     * @type {Array<WithUUIDUserPublic>}
     * @memberof FriendsRequestGetResponse
     */
    requestsFromYou: Array<WithUUIDUserPublic>;
    /**
     * 
     * @type {Array<WithUUIDUserPublic>}
     * @memberof FriendsRequestGetResponse
     */
    requestsToYou: Array<WithUUIDUserPublic>;
}

/**
 * Check if a given object implements the FriendsRequestGetResponse interface.
 */
export function instanceOfFriendsRequestGetResponse(value: object): value is FriendsRequestGetResponse {
    if (!('requestsFromYou' in value) || value['requestsFromYou'] === undefined) return false;
    if (!('requestsToYou' in value) || value['requestsToYou'] === undefined) return false;
    return true;
}

export function FriendsRequestGetResponseFromJSON(json: any): FriendsRequestGetResponse {
    return FriendsRequestGetResponseFromJSONTyped(json, false);
}

export function FriendsRequestGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendsRequestGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requestsFromYou': ((json['requestsFromYou'] as Array<any>).map(WithUUIDUserPublicFromJSON)),
        'requestsToYou': ((json['requestsToYou'] as Array<any>).map(WithUUIDUserPublicFromJSON)),
    };
}

export function FriendsRequestGetResponseToJSON(value?: FriendsRequestGetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'requestsFromYou': ((value['requestsFromYou'] as Array<any>).map(WithUUIDUserPublicToJSON)),
        'requestsToYou': ((value['requestsToYou'] as Array<any>).map(WithUUIDUserPublicToJSON)),
    };
}

