/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewPost
 */
export interface NewPost {
    /**
     * 
     * @type {string}
     * @memberof NewPost
     */
    body: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewPost
     */
    media: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewPost
     */
    title: string;
}

/**
 * Check if a given object implements the NewPost interface.
 */
export function instanceOfNewPost(value: object): value is NewPost {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function NewPostFromJSON(json: any): NewPost {
    return NewPostFromJSONTyped(json, false);
}

export function NewPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewPost {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'media': json['media'],
        'title': json['title'],
    };
}

export function NewPostToJSON(value?: NewPost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'body': value['body'],
        'media': value['media'],
        'title': value['title'],
    };
}

