/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotifContent
 */
export interface NotifContent {
    /**
     * 
     * @type {string}
     * @memberof NotifContent
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NotifContent
     */
    url: string;
}

/**
 * Check if a given object implements the NotifContent interface.
 */
export function instanceOfNotifContent(value: object): value is NotifContent {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function NotifContentFromJSON(json: any): NotifContent {
    return NotifContentFromJSONTyped(json, false);
}

export function NotifContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotifContent {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
    };
}

export function NotifContentToJSON(value?: NotifContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'url': value['url'],
    };
}

