/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    createdAt: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Post
     */
    media: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    user: string;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'createdAt': json['createdAt'],
        'media': json['media'],
        'title': json['title'],
        'user': json['user'],
    };
}

export function PostToJSON(value?: Post | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'body': value['body'],
        'createdAt': value['createdAt'],
        'media': value['media'],
        'title': value['title'],
        'user': value['user'],
    };
}

