/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupData
 */
export interface SignupData {
    /**
     * 
     * @type {string}
     * @memberof SignupData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SignupData
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupData
     */
    secret: string;
}

/**
 * Check if a given object implements the SignupData interface.
 */
export function instanceOfSignupData(value: object): value is SignupData {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function SignupDataFromJSON(json: any): SignupData {
    return SignupDataFromJSONTyped(json, false);
}

export function SignupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupData {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
        'secret': json['secret'],
    };
}

export function SignupDataToJSON(value?: SignupData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
        'secret': value['secret'],
    };
}

