/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadMediaResponse
 */
export interface UploadMediaResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof UploadMediaResponse
     */
    mediaIds: Array<string>;
}

/**
 * Check if a given object implements the UploadMediaResponse interface.
 */
export function instanceOfUploadMediaResponse(value: object): value is UploadMediaResponse {
    if (!('mediaIds' in value) || value['mediaIds'] === undefined) return false;
    return true;
}

export function UploadMediaResponseFromJSON(json: any): UploadMediaResponse {
    return UploadMediaResponseFromJSONTyped(json, false);
}

export function UploadMediaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadMediaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaIds': json['mediaIds'],
    };
}

export function UploadMediaResponseToJSON(value?: UploadMediaResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mediaIds': value['mediaIds'],
    };
}

