/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmail
 */
export interface VerifyEmail {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmail
     */
    secret: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmail
     */
    user: string;
}

/**
 * Check if a given object implements the VerifyEmail interface.
 */
export function instanceOfVerifyEmail(value: object): value is VerifyEmail {
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function VerifyEmailFromJSON(json: any): VerifyEmail {
    return VerifyEmailFromJSONTyped(json, false);
}

export function VerifyEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'secret': json['secret'],
        'user': json['user'],
    };
}

export function VerifyEmailToJSON(value?: VerifyEmail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'secret': value['secret'],
        'user': value['user'],
    };
}

