/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
} from './Notification';

/**
 * 
 * @export
 * @interface WithUUIDNotification
 */
export interface WithUUIDNotification {
    /**
     * 
     * @type {string}
     * @memberof WithUUIDNotification
     */
    uuid: string;
    /**
     * 
     * @type {Notification}
     * @memberof WithUUIDNotification
     */
    value: Notification;
}

/**
 * Check if a given object implements the WithUUIDNotification interface.
 */
export function instanceOfWithUUIDNotification(value: object): value is WithUUIDNotification {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function WithUUIDNotificationFromJSON(json: any): WithUUIDNotification {
    return WithUUIDNotificationFromJSONTyped(json, false);
}

export function WithUUIDNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithUUIDNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'value': NotificationFromJSON(json['value']),
    };
}

export function WithUUIDNotificationToJSON(value?: WithUUIDNotification | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uuid': value['uuid'],
        'value': NotificationToJSON(value['value']),
    };
}

