/* tslint:disable */
/* eslint-disable */
/**
 * GiveAndTake API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
} from './Post';

/**
 * 
 * @export
 * @interface WithUUIDPost
 */
export interface WithUUIDPost {
    /**
     * 
     * @type {string}
     * @memberof WithUUIDPost
     */
    uuid: string;
    /**
     * 
     * @type {Post}
     * @memberof WithUUIDPost
     */
    value: Post;
}

/**
 * Check if a given object implements the WithUUIDPost interface.
 */
export function instanceOfWithUUIDPost(value: object): value is WithUUIDPost {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function WithUUIDPostFromJSON(json: any): WithUUIDPost {
    return WithUUIDPostFromJSONTyped(json, false);
}

export function WithUUIDPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithUUIDPost {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'value': PostFromJSON(json['value']),
    };
}

export function WithUUIDPostToJSON(value?: WithUUIDPost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uuid': value['uuid'],
        'value': PostToJSON(value['value']),
    };
}

